# speedtest-cli ookla bin

sensor:

  - platform: command_line
    name: "Ookla Data"
    command: "/config/apps/speedtest -f json --accept-license --accept-gdpr"
    scan_interval: 1833
    command_timeout: 30
    value_template: >-
        {% set ping = value_json.ping.latency|string %}
        {% set dn = value_json.download.bandwidth|string %}
        {% set up = value_json.upload.bandwidth|string %}
        {{ ping + "," + dn + "," + up }}

template:

  - sensor:

    - name: "Ookla Ping"
      state: >-
        {% set x = states('sensor.ookla_data').split(',')[0] | float(0) %}
        {% if x > 0 %}
          {{ x|round(2) }}
        {% else %}
          {{ states('sensor.ookla_ping') }}
        {% endif %}
      icon: mdi:gauge
      unit_of_measurement: ms
      state_class: measurement

    - name: "Ookla Download"
      state: >-
        {% set x = states('sensor.ookla_data').split(',')[1] | float(0) %}
        {% if x > 0 %}
          {{ (x / 1024 / 1024 * 8)|round(2) }}
        {% else %}
          {{ states('sensor.ookla_download') }}
        {% endif %}
      icon: mdi:gauge
      unit_of_measurement: Mbps
      state_class: measurement

    - name: "Ookla Upload"
      state: >-
        {% set x = states('sensor.ookla_data').split(',')[2] | float(0) %}
        {% if x > 0 %}
          {{ (x / 1024 / 1024 * 8)|round(2) }}
        {% else %}
          {{ states('sensor.ookla_upload') }}
        {% endif %}
      icon: mdi:gauge
      unit_of_measurement: Mbps
      state_class: measurement

#eof
