// matter dev

#define USE_BERRY_INT64
#define USE_BERRY_DEBUG

#define USE_MATTER_DEVICE

#define USE_BERRY_CRYPTO_AES_CTR
#define USE_BERRY_CRYPTO_EC_P256
#define USE_BERRY_CRYPTO_HMAC_SHA256
#define USE_BERRY_CRYPTO_PBKDF2_HMAC_SHA256
#define USE_BERRY_CRYPTO_HKDF_SHA256
#define USE_BERRY_CRYPTO_SPAKE2P_MATTER

#define USE_DISCOVERY

// EOF
