[env:tasmota32_base]

[env:tasmota32_idf55_base]

;...
custom_files_upload     = tasmota/berry/modules/Partition_Manager.tapp
                          data
;...

; paste at the end of file

[env:han32lora-safeboot]
extends                 = env:tasmota32_base
board                   = esp32-solo1
board_build.app_partition_name = safeboot
build_flags             = ${env:tasmota32_base.build_flags}
                          -DFRAMEWORK_ARDUINO_SOLO1
                          -DFIRMWARE_SAFEBOOT
lib_extra_dirs          = lib/lib_ssl, lib/libesp32
lib_ignore              = ${safeboot_flags.lib_ignore}

[env:han32s3base-safeboot]
extends                 = env:tasmota32_base
board                   = esp32s3-qio_qspi
board_build.app_partition_name = safeboot
build_flags             = ${env:tasmota32_base.build_flags}
                         -DFIRMWARE_SAFEBOOT
                         -DUSE_SPI
                         -DUSE_ETHERNET
                         -UETH_TYPE
                         -DETH_TYPE=8
lib_extra_dirs          = lib/lib_ssl, lib/libesp32
lib_ignore              = ${safeboot_flags.lib_ignore}

[env:han32s3eth-safeboot]
extends                 = env:tasmota32_base
board                   = esp32s3-qio_qspi
board_build.app_partition_name = safeboot
build_flags             = ${env:tasmota32_base.build_flags}
                         -DFIRMWARE_SAFEBOOT
                         -DHAN_S3_ETH
                         -DUSE_SPI
                         -DUSE_ETHERNET
                         -UETH_TYPE
                         -DETH_TYPE=8
lib_extra_dirs          = lib/lib_ssl, lib/libesp32
lib_ignore              = ${safeboot_flags.lib_ignore}


[env:han32c6hw51-safeboot]
extends                 = env:tasmota32_idf55_base
board                   = esp32c6
board_build.app_partition_name = safeboot
build_flags             = ${env:tasmota32_idf55_base.build_flags}
                          -DFIRMWARE_SAFEBOOT
lib_extra_dirs          = lib/lib_ssl, lib/libesp32
lib_ignore              = ${safeboot_flags.lib_ignore}
custom_sdkconfig        =
                          '# CONFIG_ULP_COPROC_ENABLED is not set'
                          '# CONFIG_IEEE802154_ENABLED is not set'
                          '# CONFIG_ESP_GDBSTUB_ENABLED is not set'
                          '# CONFIG_BT_ENABLED is not set'
                          '# CONFIG_BT_NIMBLE_ENABLED is not set'
                          '# CONFIG_BT_CONTROLLER_ENABLED is not set'
                          CONFIG_BT_CONTROLLER_DISABLED=y
                          '# CONFIG_LWIP_IP_FORWARD is not set'
                          '# CONFIG_LWIP_IPV4_NAPT is not set'
                          '# CONFIG_LWIP_IPV4_NAPT_PORTMAP is not set'
                          '# CONFIG_LWIP_PPP_SUPPORT is not set'
                          '# CONFIG_ETH_SPI_ETHERNET_DM9051 is not set'
                          '# CONFIG_ETH_SPI_ETHERNET_KSZ8851SNL is not set'
custom_component_remove = ${safeboot_flags.custom_component_remove}


;...

[env:han32lora]
extends                 = env:tasmota32_base
build_flags             = ${env:tasmota32_base.build_flags}
                          -DFIRMWARE_TASMOTA32
                          -DHAN_V1
                          -DEASYHAN_TCP
                          -DEASYHAN_LORA

[env:han32c6hw51]
extends                 = env:tasmota32_idf55_base
board                   = esp32c6
build_flags             = ${env:tasmota32_idf55_base.build_flags}
                          -DFIRMWARE_TASMOTA32
                          -DHAN_C6_HW51
lib_ignore              = ${env:tasmota32_idf55_base.lib_ignore}
                          Micro-RTSP

[env:han32s3base]
extends                 = env:tasmota32_base
board                   = esp32s3-qio_qspi
build_flags             = ${env:tasmota32_base.build_flags}
                         -DFIRMWARE_TASMOTA32
lib_ignore              = ${env:tasmota32_base.lib_ignore}
                          Micro-RTSP
                          epdiy

[env:han32s3eth]
extends                 = env:tasmota32_base
board                   = esp32s3-qio_qspi
build_flags             = ${env:tasmota32_base.build_flags}
                         -DFIRMWARE_TASMOTA32
                         -DHAN_S3_ETH
                         -UETH_TYPE
                         -DETH_TYPE=8
                         -UUSE_ENHANCED_GUI_WIFI_SCAN
lib_ignore              = ${env:tasmota32_base.lib_ignore}
                          Micro-RTSP
                          epdiy

;...

; EOF
