...

    tasmota-minimal
    tasmota-4M
    tasmota-4M-tcp
    tasmota-4M-v1
    ;tasmota-4M-lora

...

; ESP32

;    han32c6hw51-safeboot
;    han32s3base-safeboot
;    han32s3eth-safeboot
;    tasmota32-safeboot

    han32c6hw51
    han32s3base
    han32s3base-ws485relay
    han32s3eth
    tasmota32
    
...

[env:tasmota32_base]

...

lib_deps =
    ModbusMaster = https://github.com/nikito7/__ModbusMaster.git#Timeout     

; EOF
